version: 2

updates:
  - package-ecosystem: npm
    directory: /nodejs
    schedule:
      interval: weekly
    open-pull-requests-limit: 0

  - package-ecosystem: uv
    directory: /python
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
